print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/evancox/Documents/Unity/BallsToTheHill/Assets/Art/Finals/house.mb"`)
{		
	file -o "/Users/evancox/Documents/Unity/BallsToTheHill/Assets/Art/Finals/house.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/evancox/Documents/Unity/BallsToTheHill/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/evancox/Documents/Unity/BallsToTheHill/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/evancox/Documents/Unity/BallsToTheHill/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
